from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from _helpers import REPO_ROOT, load_module

create_wireframe_scripts = load_module(
    "create_wireframe",
    REPO_ROOT / "skills" / "kmp-layout-system" / "scripts" / "create_wireframe.py",
)
slot_scaffold_scripts = load_module(
    "generate_slot_scaffold",
    REPO_ROOT / "skills" / "kmp-layout-system" / "scripts" / "generate_slot_scaffold.py",
)

class SlotScaffoldTests(unittest.TestCase):
    def _wireframe(self, tmp: str, pattern: str = "A") -> Path:
        root = Path(tmp)
        ls = root / "docs" / "layout-system"
        ls.mkdir(parents=True)
        f = ls / "inbox.md"
        f.write_text(create_wireframe_scripts.render("Inbox", pattern), encoding="utf-8")
        return f

    def test_contract_parsed_and_kotlin_generated(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            contract = slot_scaffold_scripts.load_contract(self._wireframe(tmp))
            kotlin = slot_scaffold_scripts.generate_kotlin(contract, "com.example.app")
            self.assertIn("GENERATED by generate_slot_scaffold", kotlin)
            self.assertIn("fun InboxLayout(", kotlin)
            for slot in ("nav", "side", "main"):
                self.assertIn(f"{slot}: @Composable () -> Unit,", kotlin)
            for bp in ("Compact", "Medium", "Expanded"):
                self.assertIn(f"WindowWidthSizeClass.{bp} ->", kotlin)
            self.assertIn("else ->", kotlin)  # exhaustive fall-back

    def test_weights_come_from_closed_set(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            f = self._wireframe(tmp)
            text = f.read_text(encoding="utf-8").replace("main: 3f", "main: 0.37f")
            f.write_text(text, encoding="utf-8")
            with self.assertRaises(ValueError):
                slot_scaffold_scripts.load_contract(f)

    def test_missing_breakpoint_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            f = self._wireframe(tmp)
            text = f.read_text(encoding="utf-8").replace("compact: [main], ", "")
            f.write_text(text, encoding="utf-8")
            with self.assertRaises(ValueError):
                slot_scaffold_scripts.load_contract(f)


if __name__ == "__main__":
    unittest.main()
